import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Grid from '@mui/material/Grid'
import Head from 'next/head'

const Developer = ()=>{
    return (
        <div>
            <Head>
                <title>Developer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid container justifyContent="space-around" style={{marginTop: '40px', marginBottom: '40px'}}>
                <Grid item xs={10} md={8}>
                    <h3 style={{textAlign: 'center', marginBottom: '40px'}}>This App Was Developed Entirely By <b style={{fontSize: '1.2em', color: '#1976D2', cursor: 'pointer'}} onClick={()=>{window.open('https://www.linkedin.com/in/amer-sulaiman/')}}>Amer Sulaiman</b></h3>
                    <pre style={{textAlign: 'left',}}>
                        <p style={{fontSize: '1.2em', fontWeight: 'bold'}}>The Used Techstack:</p>
                        &nbsp;&nbsp;&nbsp;&nbsp;- React.js/Next.js (For the frontend) <br />
                        &nbsp;&nbsp;&nbsp;&nbsp;- Redux (State Management) <br />
                        &nbsp;&nbsp;&nbsp;&nbsp;- Django (Backend) <br />
                        &nbsp;&nbsp;&nbsp;&nbsp;- Django Rest Framework (API) <br />
                        &nbsp;&nbsp;&nbsp;&nbsp;- MySQL (Database)

                        <p style={{fontSize: '1.2em', fontWeight: 'bold', marginTop: '40px'}}>What Does this website do?</p>
                        &nbsp;&nbsp;&nbsp;&nbsp;If you need to repair your car in Sweden, all you have to do is enter your car&apos;s plate number and your location. And our website will gather data from multiple famous car repair companies to find the best option based on station location, price, and available date.
                    </pre>
                    

                </Grid>
            </Grid>
        </div>
    )
}

export default Developer;